#!/bin/bash -e

fatal() {
    echo "fatal: $@" 1>&2
    exit 1
}

ubuntu_sources() {
cat >/etc/apt/sources.list<<EOF
deb http://archive.ubuntu.com/ubuntu $CODENAME main
deb http://archive.ubuntu.com/ubuntu $CODENAME-updates main
deb http://archive.ubuntu.com/ubuntu $CODENAME-security main
EOF
}

debian_sources() {
cat >/etc/apt/sources.list<<EOF
deb http://cdn.debian.net/debian/ $CODENAME main
deb http://security.debian.org/ $CODENAME/updates main
EOF
}

raspbian_sources() {
cat >/etc/apt/sources.list<<EOF
deb http://mirrordirector.raspbian.org/raspbian wheezy main firmware
deb http://archive.raspberrypi.org/debian wheezy main
EOF
}

[ -n "$CODENAME" ] || fatal "CODENAME is not set"

case "$DISTRO" in
    ubuntu) ubuntu_sources ;;
    debian) debian_sources ;;
    raspbian) rpi_sources ;;
    *) fatal "DISTRO is not set or not recognized" ;;
esac

