#!/bin/bash -e

fatal() {
    echo "fatal: $@" 1>&2
    exit 1
}

ubuntu_sources() {
cat >/etc/apt/sources.list<<EOF
deb http://de.archive.ubuntu.com/ubuntu $CODENAME main
deb http://de.archive.ubuntu.com/ubuntu $CODENAME-updates main
deb http://de.archive.ubuntu.com/ubuntu $CODENAME-security main
EOF
}

debian_sources() {
cat >/etc/apt/sources.list<<EOF
deb http://ftp.de.debian.org/debian $CODENAME main
deb http://security.debian.org/ $CODENAME/updates main
EOF
}

[ -n "$CODENAME" ] || fatal "CODENAME is not set"

case "$DISTRO" in
    ubuntu) ubuntu_sources ;;
    debian) debian_sources ;;
    *) fatal "DISTRO is not set or not recognized" ;;
esac

