#!/bin/sh -e

fatal() { echo "FATAL: $@" 1>&2; exit 1; }

lucid_patch() {
patch -f /usr/bin/dpkg-gencontrol << 'EOF'
--- /usr/bin/dpkg-gencontrol.orig       2010-04-15 17:23:43.000000000 +0000
+++ /usr/bin/dpkg-gencontrol    2010-06-03 12:11:23.000000000 +0000
@@ -291,6 +291,7 @@
     if (!$c) {
         chdir("$packagebuilddir") ||
             syserr(_g("chdir for du to \`%s'"), $packagebuilddir);
+        system("find -type f | xargs touch"); # workaround for evil aufs bug
         exec("du", "-k", "-s", ".") or syserr(_g("exec %s"), "du");
     }
     my $duo = '';
EOF
}

lenny_patch() {
patch -f /usr/bin/dpkg-gencontrol << 'EOF'
--- /usr/bin/dpkg-gencontrol.orig       2010-06-23 17:51:35.000000000 +0000
+++ /usr/bin/dpkg-gencontrol    2010-06-23 17:52:28.000000000 +0000
@@ -288,6 +288,7 @@
     if (!$c) {
         chdir("$packagebuilddir") ||
             syserr(_g("chdir for du to \`%s'"), $packagebuilddir);
+        system("find -type f | xargs touch"); # workaround for evil aufs bug
         exec("du","-k","-s",".") or &syserr(_g("exec du"));
     }
     my $duo = '';
EOF
}

squeeze_patch() {
patch -f /usr/bin/dpkg-gencontrol << 'EOF'
--- dpkg-gencontrol.orig        2012-02-16 11:15:44.000000000 +0000
+++ dpkg-gencontrol     2012-02-16 11:16:18.000000000 +0000
@@ -301,6 +301,7 @@
     if (!$c) {
         chdir("$packagebuilddir") ||
             syserr(_g("chdir for du to \`%s'"), $packagebuilddir);
+        system("find -type f | xargs touch"); # workaround for evil aufs bug
         exec("du", "-k", "-s", ".") or syserr(_g("exec %s"), "du");
     }
     my $duo = '';
EOF
}

wheezy_patch() {
patch -f /usr/bin/dpkg-gencontrol << 'EOF'
--- dpkg-gencontrol.orig        2012-11-12 11:26:32.000000000 +0200
+++ dpkg-gencontrol     2012-11-12 11:27:30.000000000 +0200
@@ -323,6 +323,7 @@
     if (!$c) {
         chdir("$packagebuilddir") ||
             syserr(_g("chdir for du to \`%s'"), $packagebuilddir);
+        system("find -type f | xargs touch"); # workaround for evil aufs bug
         exec("du", "-k", "-s", "--apparent-size", ".") or
             syserr(_g("unable to execute %s"), "du");
     }
EOF
}

jessie_patch() {
patch -f /usr/bin/dpkg-gencontrol << 'EOF'
--- dpkg-gencontrol.orig        2015-04-21 13:43:52.000000000 +0300
+++ dpkg-gencontrol     2015-04-21 13:45:28.000000000 +0300
@@ -341,6 +341,7 @@
     if (!$c) {
         chdir("$packagebuilddir")
             or syserr(_g("chdir for du to \`%s'"), $packagebuilddir);
+        system("find -type f | xargs touch"); # workaround for evil aufs bug
         exec('du', '-k', '-s', '--apparent-size', '.')
             or syserr(_g('unable to execute %s'), 'du');
     }
EOF
}

case "$CODENAME" in
    lucid)      lucid_patch ;;
    lenny)      lenny_patch ;;
    squeeze)    squeeze_patch ;;
    wheezy)     wheezy_patch ;;
    jessie)     jessie_patch ;;
    stretch)    : ;; # uses overlayfs instead of aufs
    *) fatal "CODENAME is not set or not recognized" ;;
esac

